name: Deploy to Public Pages Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private source
        uses: actions/checkout@v4

      - name: Set up Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        if: hashFiles('package.json') != ''
        run: npm ci || npm install

      - name: Build
        if: hashFiles('package.json') != ''
        run: npm run build || echo "skip build"

      - name: Detect publish dir
        id: detect
        run: |
          if [ -d dist ]; then
            echo "dir=dist" >> $GITHUB_OUTPUT
          elif [ -d build ]; then
            echo "dir=build" >> $GITHUB_OUTPUT
          else
            echo "dir=." >> $GITHUB_OUTPUT
          fi

      - name: Push to public repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: GUGUPORT/portfolio
          publish_branch: main
          publish_dir: ${{ steps.detect.outputs.dir }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          force_orphan: true
